# Generated by Django 4.0.5 on 2022-06-25 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torta', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Torta',
        ),
    ]
